apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aws-ec2-instance
  title: AWS EC2 Instance
  description: Template to provision an AWS EC2 instance using Terraform
  tags:
    - aws
    - ec2
    - terraform
    - infrastructure
spec:
  owner: user:guest
  type: infrastructure
  parameters:
    - title: Basic Information
      required:
        - name
        - description
      properties:
        name:
          title: Name
          type: string
          description: Unique name for this EC2 instance
          pattern: '^([a-zA-Z][a-zA-Z0-9]*[-_]?[a-zA-Z0-9]+)*$'
          ui:autofocus: true
          ui:help: 'Hint: Use a descriptive name for your EC2 instance'
        description:
          title: Description
          type: string
          description: Brief description of the EC2 instance purpose
    - title: AWS Configuration
      required:
        - aws_region
      properties:
        aws_region:
          title: AWS Region
          type: string
          description: AWS region where the EC2 instance will be deployed
          default: us-east-1
          enum:
            - us-east-1
            - us-west-2
            - eu-west-1
          enumNames:
            - US East (N. Virginia)
            - US West (Oregon)
            - Europe (Ireland)
        key_pair_name:
          title: Key Pair Name (Optional)
          type: string
          description: Name of existing AWS key pair for SSH access (leave empty if none)
    - title: Repository Information
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: fetch
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: https://github.com/kjchandan/Backstage_aws-ec2/tree/main/skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          aws_region: ${{ parameters.aws_region }}
          key_pair_name: ${{ parameters.key_pair_name }}
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
